In [1]:
import pandas as pd
import numpy as np

In [35]:
mat_1 = np.array([[4, 3], [1, 2]])

In [36]:
mat_1

array([[4, 3],
       [1, 2]])

In [37]:
from sklearn.decomposition import NMF

In [38]:
model = NMF(n_components=2, 
            init='random', 
            random_state=0)
W = model.fit_transform(mat_1)

In [39]:
W.shape

(2, 2)

In [40]:
W

array([[1.62399844, 0.87824122],
       [0.17939376, 0.73962584]])

In [41]:
H = model.components_

In [42]:
H

array([[1.99333935, 0.44308093],
       [0.86856871, 2.5965983 ]])

In [43]:
np.round(W@H, 2)

array([[4., 3.],
       [1., 2.]])